### ISSUE TITLE
Falha ao iniciar

### ISSUE THREAD

**Issue by progerio** [cabaag/ionic-preview#19]
![captura de tela de 2016-05-28 18-24-11](https://cloud.githubusercontent.com/assets/526290/15630049/89c97fc4-2501-11e6-94c4-5a1a6f64e157.png)

**Comment by hpandelo** [comment]
Same shit here

**Comment by caiquecsx** [comment]
go to Atom packges > Ionic Preview them click in view code 
edit ionic.coffee and ionic-view.coffe where you have
atom.workspace.open "ionic://localhost:8100"
change the localhost, for whatever you have when you start the serve and it will work :dancer:

**Comment by mfdeveloper** [comment]
@caiquecsx That's works, but I think this approach is not recommended. A better solution is that this plugin get a configuration from the **Atom Settings** packages panel or a `json` file with the address and port

@cabaag Do you think in add this parameters to configure this plugin?

**Comment by cabaag** [comment]
@mfdeveloper thanks for your recommendation, now you can customize address and port from settings
