### ISSUE TITLE
Last version 0.5.1 latency

### ISSUE THREAD

**Issue by 0nza1101** [cabaag/ionic-preview#20]
Hi,
I installed the lastest version of ionic preview nicely but when I start with Ctrl+P ionic-preview, my PC start lagging, im stuck with a slow mouse mouvement and so on.

So I installed the previous version wich was working like a charm since no fix available.

Thanks.

**Comment by cabaag** [comment]
Hi, I know, the problem is that atom initialize multiple times ionic-preview and with each of them starts an ionic process, i'm working to fix this, will be helpful if send some pics of ur task manager

**Comment by 0nza1101** [comment]
Thanks for your reply first,
It was hard to take some pics but I got it, the problem that u discribed is exactly wath atom do. There is multiple instance of cmd and Node.Js. I think there is an infinite loop somewhere.
![capture](https://cloud.githubusercontent.com/assets/13056641/17173692/a5318304-53fc-11e6-978a-ec5631234e70.PNG)
![2capture](https://cloud.githubusercontent.com/assets/13056641/17173699/a9e1dfa2-53fc-11e6-91da-8f7c4afc48ed.PNG)

**Comment by maryxb** [comment]
how I can reinstall the old version?

**Comment by 0nza1101** [comment]
Open cmd as administrator then type `apm install ionic-preview@v0.3.6`

**Comment by maryxb** [comment]
doesn´t work :(

![image](https://cloud.githubusercontent.com/assets/6178091/17369074/1967c998-596d-11e6-9de2-d2920d729523.png)

**Comment by 0nza1101** [comment]
Sorry for the late reply, the command is `apm install ionic-preview@0.3.6` just delete the 'v'

**Comment by cabaag** [comment]
Update and try again, now you'll have only one process for ionic
