### ISSUE TITLE
ionic-preview asking to start ionic serve even though it is already running

### ISSUE THREAD

**Issue by AlexKo99** [cabaag/ionic-preview#21]
Hi, I installed the ionic-preview package today and it doesn't work.
I navigate to my project in the nodejs command line and execute ionic serve -b. everything works fine (I even reinstalled ionic after I saw that there was a problem with the live reload server). Then I open the ionic preview in atom and it demands to start ionic serve.if I set in the package settings "auto start serve" , atom freezes up and the preview tab keeps reloading when opening the preview.

what can be done about it?
Thank you.

**Comment by alexandrekrugera** [comment]
Hi, I think you need to configure your _uri_ address of the _atom.workspace.open_ method inside _ionic.coffee_ and _ionic-view.coffee_ lib.

So to do this you need to go in your installed packages (Ctrl + Shift + P and type installed) then find _ionic-preview_ package and click on _View Code_. Find _ionic.coffee_ and _ionic-view.coffee_ on lib.

You will see code like this inside them:

```
    atom.workspace.open "ionic://192.168.0.100:8100", split: "right"
```

You need to change the address to your ionic running server address. If is it running on localhost, change to localhost:port.

Save, rerun atom and server. Then Ctrl + Shift + P and type Preview.
I hope it works.

**Comment by AlexKo99** [comment]
It worked! Thank you!

**Comment by cabaag** [comment]
Now you can customize the address and port for your serve, just write it and the ionic-preview will load that location

**Comment by luccas-freitas** [comment]
Anynone can help? I have the same issue and the answer above didn't work.

**Comment by markhoward02** [comment]
Adding these settings to the bottom of my User Settings file in VS Code did the trick:
    "ionic-preview.host": "http://localhost",
    "ionic-preview.port": 8100

**Comment by lucasfre** [comment]
@markhoward02 , tks for the answer, you helped me!
