### ISSUE TITLE
Suggestion: Adding an option to change screen size, layout and platform

### ISSUE THREAD

**Issue by YogliB** [cabaag/ionic-preview#24]
Hi just started using Ionic, and the preview is very comfortable, but I have no idea whic device it emulates.
I would be very helpful if we could choose the screen size (or a specific device), the orientation and platform (Android/iOS/Windows).

**Comment by cabaag** [comment]
That is a TODO of the package, I'll design more devices as soon as possible, the default view is an iPhone 5
